# Builds DOCUMENTS.md: a list of every file in the 11 section folders,
# with Preview and Download links on github.com.
# Works with Windows PowerShell 5.1; no installs needed. Run from the repo root:
#   powershell -ExecutionPolicy Bypass -File scripts/build-documents-page.ps1

$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$baseUrl  = 'https://github.com/seonarandomclarity/FormationMarkets'

# Folder names and display titles are fixed. Listed in the order they appear on the page.
$sections = @(
    @{ Folder = '01-roadmap';              Title = 'Roadmap' },
    @{ Folder = '02-technology';           Title = 'Technology' },
    @{ Folder = '03-company-structures';   Title = 'Company Structures' },
    @{ Folder = '04-team-and-hiring-plan'; Title = 'Team and Hiring Plan' },
    @{ Folder = '05-liquidity-curve';      Title = 'Liquidity Curve' },
    @{ Folder = '06-why-company-kpis';     Title = 'Why Company KPIs?' },
    @{ Folder = '07-regulatory';           Title = 'Regulatory' },
    @{ Folder = '08-economics';            Title = 'Economics' },
    @{ Folder = '09-target-icps';          Title = 'Target ICPs' },
    @{ Folder = '10-use-of-funds';         Title = 'Use of Funds' },
    @{ Folder = '11-documents-vdr';        Title = 'Documents (VDR)' }
)

# Path relative to the repo root, with forward slashes (e.g. "01-roadmap/Plan 2026.pdf").
function Get-RelativePath([string]$fullPath) {
    $fullPath.Substring($repoRoot.Length).TrimStart('\', '/') -replace '\\', '/'
}

# URL-encode each path segment separately so spaces, brackets etc. work but "/" stays as-is.
# EscapeDataString in PowerShell 5.1 leaves ( ) ! * ' alone, and "(" / ")" can break Markdown links, so encode them too.
function ConvertTo-UrlPath([string]$relativePath) {
    $segments = $relativePath -split '/' | ForEach-Object {
        [Uri]::EscapeDataString($_).Replace('(', '%28').Replace(')', '%29').Replace('!', '%21').Replace('*', '%2A').Replace("'", '%27')
    }
    $segments -join '/'
}

# Backslash-escape characters that Markdown would otherwise treat as formatting or table borders.
function ConvertTo-MarkdownText([string]$text) {
    $text -replace '([\\`*_\[\]<>|#])', '\$1'
}

function Format-FileSize([long]$bytes) {
    $invariant = [Globalization.CultureInfo]::InvariantCulture
    if ($bytes -ge 1MB) {
        return ($bytes / 1MB).ToString('0.0', $invariant) + ' MB'
    }
    $kb = $bytes / 1KB
    if ($bytes -gt 0 -and $kb -lt 0.1) { $kb = 0.1 }
    return $kb.ToString('0.0', $invariant) + ' KB'
}

function Add-FileTable($lines, $files) {
    $lines.Add('| File | Type | Size | Preview | Download |')
    $lines.Add('| --- | --- | --- | --- | --- |')
    foreach ($file in $files) {
        $urlPath = ConvertTo-UrlPath (Get-RelativePath $file.FullName)
        if ($file.Extension) { $type = $file.Extension.TrimStart('.').ToUpperInvariant() } else { $type = 'File' }
        $name = ConvertTo-MarkdownText $file.Name
        $size = Format-FileSize $file.Length
        $lines.Add("| $name | $type | $size | [Preview]($baseUrl/blob/main/$urlPath) | [Download]($baseUrl/raw/main/$urlPath) |")
    }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('> This page is generated by scripts/build-documents-page.ps1. Do not edit by hand.')
$lines.Add('')
$lines.Add('# All documents')
$lines.Add('')
$lines.Add('[Back to home](README.md)')

foreach ($section in $sections) {
    $sectionDir = Join-Path $repoRoot $section.Folder
    $lines.Add('')
    $lines.Add("## [$($section.Title)]($($section.Folder)/README.md)")
    $lines.Add('')

    $files = @()
    if (Test-Path -LiteralPath $sectionDir) {
        $files = @(Get-ChildItem -LiteralPath $sectionDir -Recurse -File | Where-Object { $_.Name -ne 'README.md' })
    }
    if ($files.Count -eq 0) {
        $lines.Add('No documents yet.')
        continue
    }

    # Files directly in the section folder come first, then one sub-group per subfolder.
    $groups = $files | Group-Object DirectoryName | Sort-Object Name
    $first = $true
    foreach ($group in $groups) {
        if (-not $first) { $lines.Add('') }
        $first = $false
        if ($group.Name -ne $sectionDir) {
            $subPath = $group.Name.Substring($sectionDir.Length).TrimStart('\', '/') -replace '\\', ' / '
            $lines.Add("### $(ConvertTo-MarkdownText $subPath)")
            $lines.Add('')
        }
        Add-FileTable $lines ($group.Group | Sort-Object Name)
    }
}

$outPath = Join-Path $repoRoot 'DOCUMENTS.md'
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[IO.File]::WriteAllText($outPath, (($lines -join "`n") + "`n"), $utf8NoBom)
Write-Host "Wrote $outPath"
